version: '1.0.{build}'
branches:
    only:
        - master
max_jobs: 1
install:
    - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
platform: Any CPU
build: off
test_script:
    - nmake /F NMakefile test-all
before_deploy:
    - nmake /F NMakefile clean latria
deploy:
    provider: GitHub
    auth_token:
        secure: VXCmu2vAN8L+rOshz8ayzNeplJ22ClEiL3hJ5RnXEq9N9wyZU2htV5h8NX1i2XJq
    artifact: build\latria.exe
    on:
        branch: master
        appveyor_repo_tag: true
    force_update: true # allows us to add latria.exe to an existing release
