language: c
compiler:
    - gcc
    - clang
script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make mac-test; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make linux-test; fi
os:
    - osx
    - linux
