language: c
compiler:
    - gcc
script:
    - make linux-test
matrix:
    include:
        # osx
        - os: osx
        osx_image: xcode9
        env:
            - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

        # linux
        - os: linux
        addons:
        apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.9
        env:
            - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
